# Generated by Django 2.2 on 2023-03-06 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attributes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noun', models.CharField(max_length=25)),
                ('noun2', models.CharField(max_length=25)),
                ('verb', models.CharField(max_length=25)),
                ('verb2', models.CharField(max_length=25)),
                ('adjective', models.CharField(max_length=25)),
                ('adjective2', models.CharField(max_length=25)),
                ('item', models.CharField(max_length=25)),
                ('place', models.CharField(max_length=25)),
                ('animal', models.CharField(max_length=25)),
            ],
        ),
    ]
